fprintf (fs, "<HTML>\n");
fprintf (fs, "\n");
fprintf (fs, "<HEAD>\n");
fprintf (fs, "\n");
fprintf (fs, "<TITLE>TelefonKurzwahlliste</TITLE>\n");
fprintf (fs, "\n");
fprintf (fs, "<SCRIPT language=\"JavaScript\" src=\"js_fade.txt\" type=\"text/JavaScript\"></SCRIPT>\n");
fprintf (fs, "<SCRIPT language=\"JavaScript\" src=\"js_menu.txt\" type=\"text/JavaScript\"></SCRIPT>\n");
fprintf (fs, "\n");
fprintf (fs, "<SCRIPT language=\"JavaScript\">\n");
fprintf (fs, "<!--\n");
fprintf (fs, "\n");
fprintf (fs, "function chk(){ \n");
fprintf (fs, "}\n");
fprintf (fs, "\n");
fprintf (fs, "function txtHinw(feldname){\n");
fprintf (fs, "return \"In Zeile '\" + feldname + \"' wurde eine falsche Eingabe vorgenommen. \" + \n");
fprintf (fs, "\"\nDie korrekte Eingabe ist notwendig, um die Kurzwahlliste verwenden zu können.\";\n");
fprintf (fs, "}\n");
fprintf (fs, "\n");
fprintf (fs, "function stOk(){\n");
fprintf (fs, "\n");
fprintf (fs, "document.getElementById(\"c_verzoeg1\").style.visibility='visible';\n");
fprintf (fs, "document.getElementById(\"c_verzoeg2\").style.visibility='visible';\n");
fprintf (fs, "setTimeout(\"stZrk()\",top.frames[0].verzoeg);\n");
fprintf (fs, "}\n");
fprintf (fs, "\n");
fprintf (fs, "function stZrk(){\n");
fprintf (fs, "top.frames[2].location.href = \"hcti_telefon.htm\";\n");
fprintf (fs, "}\n");
fprintf (fs, "\n");
fprintf (fs, "//-->\n");
fprintf (fs, "</SCRIPT>\n");
fprintf (fs, "\n");
fprintf (fs, "<LINK rel=\"stylesheet\" href=\"style.css\" type=\"text/css\">\n");
fprintf (fs, "\n");
fprintf (fs, "<STYLE type=\"text/css\">\n");
fprintf (fs, "<!--\n");
fprintf (fs, "\n");
fprintf (fs, "#scroll{WIDTH: 400px; HEIGHT: 368px; OVERFLOW: scroll;}\n");
fprintf (fs, "\n");
fprintf (fs, "//-->\n");
fprintf (fs, "</STYLE>\n");
fprintf (fs, "\n");
fprintf (fs, "</HEAD>\n");
fprintf (fs, "\n");
fprintf (fs, "<BODY onload=chk()>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=c_Frame>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=c_border>\n");
fprintf (fs, "<DIV id=c_pfad>Telefonie / Kurzwahlliste</DIV>\n");
fprintf (fs, "<DIV id=c_titel>&nbsp;&nbsp;KW&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bezeichnung&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rufnummer&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Netze</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=scroll>\n");
fprintf (fs, "<SCRIPT language=\"JavaScript\">\n");
fprintf (fs, "<!--\n");
fprintf (fs, "\n");
fprintf (fs, "for (i=0;i<100;i++){\n");
fprintf (fs, "var divart = \"c_std\";\n");
fprintf (fs, "var endf = \"\";\n");
fprintf (fs, "if (i==100-1){\n");
fprintf (fs, "divart = \"c_last\";\n");
fprintf (fs, "endf = \"</form>\";\n");
fprintf (fs, "}\n");
fprintf (fs, "document.write(\n");
fprintf (fs, "'<DIV id=' + divart + '>' +\n");
fprintf (fs, "'<table border=\"0\" cellpadding=\"0\" cellspacing=\"2\">' +\n");
fprintf (fs, "'<tr onmouseover=i_showElem(1) onmouseout=i_showElem(0)>');\n");
fprintf (fs, "			if (i<10){\n");
fprintf (fs, "				document.write('<td width=\"30\" align=\"center\">0' + i + '#</td>');\n");
fprintf (fs, "			}\n");
fprintf (fs, "			else{\n");
fprintf (fs, "				document.write('<td width=\"30\" align=\"center\">' + i + '#</td>');\n");
fprintf (fs, "			}\n");
fprintf (fs, "			document.write(\n");
fprintf (fs, "'<td width=\"12\"></td>' +\n");
fprintf (fs, "'<td width=\"120\"><input type=\"text\" name=\"T1\" size=\"12\" maxlength=\"20\"></td>' +\n");
fprintf (fs, "'<td width=\"120\"><input type=\"text\" name=\"T2\" size=\"12\" maxlength=\"20\"></td>' +\n");
fprintf (fs, "'<td>' +\n");
fprintf (fs, "				'<select name=\"D1\" size=\"1\">' +\n");
fprintf (fs, "					'<option>Internet</option>' +\n");
fprintf (fs, "					'<option>Festnetz</option>' +\n");
fprintf (fs, "					'<option>Beide</option>' +\n");
fprintf (fs, "				'</select>' +\n");
fprintf (fs, "			'</td>' +\n");
fprintf (fs, "endf +\n");
fprintf (fs, "'</tr>' +\n");
fprintf (fs, "'</table>' +\n");
fprintf (fs, "'</DIV>');\n");
fprintf (fs, "}\n");
fprintf (fs, "\n");
fprintf (fs, "//-->\n");
fprintf (fs, "</SCRIPT>\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=c_foot></DIV>\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=c_verzoeg1></DIV>\n");
fprintf (fs, "<DIV id=c_verzoeg2></DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=t_Frame>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=t_but1 onclick=startseite() onmouseover=rahmen(1,1) onmouseout=rahmen(0,1)>&lt;&lt;&nbsp;&nbsp;&lt;&lt;</DIV>\n");
fprintf (fs, "<DIV id=t_but3 onclick=stZrk() onmouseover=rahmen(1,3) onmouseout=rahmen(0,3)>Zur&uuml;ck &lt;&lt;</DIV>\n");
fprintf (fs, "<DIV id=t_but4 onclick=stOk() onmouseover=rahmen(1,4) onmouseout=rahmen(0,4)>Speichern &lt;&lt;</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=i_Frame>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=i_content>\n");
fprintf (fs, "<h2>Kurzwahlliste</h2>\n");
fprintf (fs, "<p>Hier können Sie die Rufnummern eintragen die Sie dann per Kurzwahl anwählen können.</p>\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=i_content1>\n");
fprintf (fs, "<h2>Kurzwahlliste</h2>\n");
fprintf (fs, "<p><b>KW</b><br>\n");
fprintf (fs, "	Mit der Kurzwahl können Sie die Rufnummer anwählen, die in dem Feld Rufnummer eingetragen ist.</p>\n");
fprintf (fs, "<p><b>Bezeichnung</b><br>\n");
fprintf (fs, "	Damit Sie wissen um welche Rufnummer es sich handelt, vergeben Sie bitte eine Bezeichnung.</p>\n");
fprintf (fs, "<p><b>Rufnummer</b><br>\n");
fprintf (fs, "	Tragen Sie hier die Rufnummer ein, die Sie per Kurzwahl erreichen möchten.</p>\n");
fprintf (fs, "<p><b>Netze</b><br>\n");
fprintf (fs, "	Wählen Sie das Netz aus, über welches die Anwahl erfolgen soll. \n");
fprintf (fs, "	Wenn Sie beide auswählen, dann wird die Verbindung über eine freie Leitung versucht aufzubauen. \n");
fprintf (fs, "	Die Priorität der Leitungsbelegung können Sie unter dem Menüpunkt: 'Rufnummer gehend' festlegen.  </p>\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "</BODY>\n");
fprintf (fs, "\n");
fprintf (fs, "</HTML>\n");
fprintf (fs, "<HTML>\n");
fprintf (fs, "\n");
fprintf (fs, "<HEAD>\n");
fprintf (fs, "\n");
fprintf (fs, "<TITLE>TelefonKurzwahlliste</TITLE>\n");
fprintf (fs, "\n");
fprintf (fs, "<SCRIPT language=\"JavaScript\" src=\"js_fade.txt\" type=\"text/JavaScript\"></SCRIPT>\n");
fprintf (fs, "<SCRIPT language=\"JavaScript\" src=\"js_menu.txt\" type=\"text/JavaScript\"></SCRIPT>\n");
fprintf (fs, "\n");
fprintf (fs, "<SCRIPT language=\"JavaScript\">\n");
fprintf (fs, "<!--\n");
fprintf (fs, "\n");
fprintf (fs, "function chk(){ \n");
fprintf (fs, "}\n");
fprintf (fs, "\n");
fprintf (fs, "function txtHinw(feldname){\n");
fprintf (fs, "return \"In Zeile '\" + feldname + \"' wurde eine falsche Eingabe vorgenommen. \" + \n");
fprintf (fs, "\"\nDie korrekte Eingabe ist notwendig, um die Kurzwahlliste verwenden zu können.\";\n");
fprintf (fs, "}\n");
fprintf (fs, "\n");
fprintf (fs, "function stOk(){\n");
fprintf (fs, "\n");
fprintf (fs, "var loc = 'voipcfg.cmd?action=outset&s';\n");
fprintf (fs, "\n");
fprintf (fs, "for (i=0;i<100;i++){\n");
fprintf (fs, "loc = loc + 'QCAL_' + i + '=' + encodeUrl(document.F1.T1[i].value) + '&';\n");
fprintf (fs, "	loc = loc + 'QDES_' + i + '=' + encodeUrl(document.F1.T2[i].value) + '&';\n");
fprintf (fs, "	}\n");
fprintf (fs, "	for (j=0; j<99; j++)\n");
fprintf (fs, "		loc = loc + 'QSEL_' + j + '=' + document.F1.D1[j].selectedIndex + '&';\n");
fprintf (fs, "\n");
fprintf (fs, "loc = loc + 'QSEL_99=' +  encodeUrl(document.F1.elements[99].value);\n");
fprintf (fs, "\n");
fprintf (fs, "alert(loc);\n");
fprintf (fs, "var code = 'this.location.assign(\"' + loc + '\")';\n");
fprintf (fs, "eval(code);  \n");
fprintf (fs, "document.getElementById(\"c_verzoeg1\").style.visibility='visible';\n");
fprintf (fs, "document.getElementById(\"c_verzoeg2\").style.visibility='visible';\n");
fprintf (fs, "}\n");
fprintf (fs, "\n");
fprintf (fs, "function stZrk(){\n");
fprintf (fs, "top.frames[2].location.href = \"hcti_telefon.htm\";\n");
fprintf (fs, "}\n");
fprintf (fs, "\n");
fprintf (fs, "//-->\n");
fprintf (fs, "</SCRIPT>\n");
fprintf (fs, "\n");
fprintf (fs, "<LINK rel=\"stylesheet\" href=\"style.css\" type=\"text/css\">\n");
fprintf (fs, "\n");
fprintf (fs, "<STYLE type=\"text/css\">\n");
fprintf (fs, "<!--\n");
fprintf (fs, "\n");
fprintf (fs, "#scroll{WIDTH: 400px; HEIGHT: 368px; OVERFLOW: scroll;}\n");
fprintf (fs, "\n");
fprintf (fs, "//-->\n");
fprintf (fs, "</STYLE>\n");
fprintf (fs, "\n");
fprintf (fs, "</HEAD>\n");
fprintf (fs, "\n");
fprintf (fs, "<BODY onload=chk()>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=c_Frame>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=c_border>\n");
fprintf (fs, "<DIV id=c_pfad>Telefonie / Kurzwahlliste</DIV>\n");
fprintf (fs, "<DIV id=c_titel>&nbsp;&nbsp;KW&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bezeichnung&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rufnummer&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Netze</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=scroll>\n");
fprintf (fs, "<SCRIPT language=\"JavaScript\">\n");
fprintf (fs, "<!--\n");
fprintf (fs, "\n");
fprintf (fs, "for (i=0;i<100;i++){\n");
fprintf (fs, "var divart = \"c_std\";\n");
fprintf (fs, "var endf = \"\";\n");
fprintf (fs, "if (i==100-1){\n");
fprintf (fs, "divart = \"c_last\";\n");
fprintf (fs, "endf = \"</form>\";\n");
fprintf (fs, "}\n");
fprintf (fs, "document.write(\n");
fprintf (fs, "'<DIV id=' + divart + '>' +\n");
fprintf (fs, "'<table border=\"0\" cellpadding=\"0\" cellspacing=\"2\">' +\n");
fprintf (fs, "'<tr onmouseover=i_showElem(1) onmouseout=i_showElem(0)>');\n");
fprintf (fs, "			if (i<10){\n");
fprintf (fs, "				document.write('<td width=\"30\" align=\"center\">0' + i + '#</td>');\n");
fprintf (fs, "			}\n");
fprintf (fs, "			else{\n");
fprintf (fs, "				document.write('<td width=\"30\" align=\"center\">' + i + '#</td>');\n");
fprintf (fs, "			}\n");
fprintf (fs, "			document.write(\n");
fprintf (fs, "'<td width=\"12\"></td>' +\n");
fprintf (fs, "'<td width=\"120\"><input type=\"text\" name=\"T1\" size=\"12\" maxlength=\"20\"></td>' +\n");
fprintf (fs, "'<td width=\"120\"><input type=\"text\" name=\"T2\" size=\"12\" maxlength=\"20\"></td>' +\n");
fprintf (fs, "'<td>' +\n");
fprintf (fs, "				'<select name=\"D1\" size=\"1\">' +\n");
fprintf (fs, "					'<option>Internet</option>' +\n");
fprintf (fs, "					'<option>Festnetz</option>' +\n");
fprintf (fs, "					'<option>Beide</option>' +\n");
fprintf (fs, "				'</select>' +\n");
fprintf (fs, "			'</td>' +\n");
fprintf (fs, "endf +\n");
fprintf (fs, "'</tr>' +\n");
fprintf (fs, "'</table>' +\n");
fprintf (fs, "'</DIV>');\n");
fprintf (fs, "}\n");
fprintf (fs, "\n");
fprintf (fs, "//-->\n");
fprintf (fs, "</SCRIPT>\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=c_foot></DIV>\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=c_verzoeg1></DIV>\n");
fprintf (fs, "<DIV id=c_verzoeg2></DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=t_Frame>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=t_but1 onclick=startseite() onmouseover=rahmen(1,1) onmouseout=rahmen(0,1)>&lt;&lt;&nbsp;&nbsp;&lt;&lt;</DIV>\n");
fprintf (fs, "<DIV id=t_but3 onclick=stZrk() onmouseover=rahmen(1,3) onmouseout=rahmen(0,3)>Zur&uuml;ck &lt;&lt;</DIV>\n");
fprintf (fs, "<DIV id=t_but4 onclick=stOk() onmouseover=rahmen(1,4) onmouseout=rahmen(0,4)>Speichern &lt;&lt;</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=i_Frame>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=i_content>\n");
fprintf (fs, "<h2>Kurzwahlliste</h2>\n");
fprintf (fs, "<p>Hier können Sie die Rufnummern eintragen die Sie dann per Kurzwahl anwählen können.</p>\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "<DIV id=i_content1>\n");
fprintf (fs, "<h2>Kurzwahlliste</h2>\n");
fprintf (fs, "<p><b>KW</b><br>\n");
fprintf (fs, "	Mit der Kurzwahl können Sie die Rufnummer anwählen, die in dem Feld Rufnummer eingetragen ist.</p>\n");
fprintf (fs, "<p><b>Bezeichnung</b><br>\n");
fprintf (fs, "	Damit Sie wissen um welche Rufnummer es sich handelt, vergeben Sie bitte eine Bezeichnung.</p>\n");
fprintf (fs, "<p><b>Rufnummer</b><br>\n");
fprintf (fs, "	Tragen Sie hier die Rufnummer ein, die Sie per Kurzwahl erreichen möchten.</p>\n");
fprintf (fs, "<p><b>Netze</b><br>\n");
fprintf (fs, "	Wählen Sie das Netz aus, über welches die Anwahl erfolgen soll. \n");
fprintf (fs, "	Wenn Sie beide auswählen, dann wird die Verbindung über eine freie Leitung versucht aufzubauen. \n");
fprintf (fs, "	Die Priorität der Leitungsbelegung können Sie unter dem Menüpunkt: 'Rufnummer gehend' festlegen.  </p>\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "</DIV>\n");
fprintf (fs, "\n");
fprintf (fs, "</BODY>\n");
fprintf (fs, "\n");
fprintf (fs, "</HTML>\n");
